// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD48LyWmyT9WPU5AQPG71XqsBMCkX_0BeI',
    appId: '1:422592305835:web:cf816d73f522dc7045f5ee',
    messagingSenderId: '422592305835',
    projectId: 'authapp-flutlearn',
    authDomain: 'authapp-flutlearn.firebaseapp.com',
    storageBucket: 'authapp-flutlearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOCzGyFDQ17hQg-_ilM2dvGXMODP2CreI',
    appId: '1:422592305835:android:cead9166a087bb9745f5ee',
    messagingSenderId: '422592305835',
    projectId: 'authapp-flutlearn',
    storageBucket: 'authapp-flutlearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-xoMHl75p4xvld9v_486XQHbTCYfzyNY',
    appId: '1:422592305835:ios:45e7c07fb07047ae45f5ee',
    messagingSenderId: '422592305835',
    projectId: 'authapp-flutlearn',
    storageBucket: 'authapp-flutlearn.appspot.com',
    iosBundleId: 'com.flutlearn.authapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-xoMHl75p4xvld9v_486XQHbTCYfzyNY',
    appId: '1:422592305835:ios:45e7c07fb07047ae45f5ee',
    messagingSenderId: '422592305835',
    projectId: 'authapp-flutlearn',
    storageBucket: 'authapp-flutlearn.appspot.com',
    iosBundleId: 'com.flutlearn.authapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD48LyWmyT9WPU5AQPG71XqsBMCkX_0BeI',
    appId: '1:422592305835:web:a71cc33ed4f80f1a45f5ee',
    messagingSenderId: '422592305835',
    projectId: 'authapp-flutlearn',
    authDomain: 'authapp-flutlearn.firebaseapp.com',
    storageBucket: 'authapp-flutlearn.appspot.com',
  );
}
